MAKE = make

all: lunartec sim900 apc220

clean:
	$(MAKE) -C lunartec clean
	$(MAKE) -C sabertooth clean
	$(MAKE) -C sim900 clean
	$(MAKE) -C apc220 clean

apc220:
	$(MAKE) -C apc220

sim900: 
	$(MAKE) -C sim900

sabertooth:
	$(MAKE) -C sabertooth

lunartec:
	$(MAKE) -C lunartec
