MAKE = make

all: 1wire i2c rs232

clean:
	$(MAKE) -C 1wire clean
	$(MAKE) -C ant clean
	$(MAKE) -C apc220 clean
	$(MAKE) -C elexol clean
	$(MAKE) -C hd44780 clean
	$(MAKE) -C i2c clean
	$(MAKE) -C joysticks clean
	$(MAKE) -C rs232 clean
	$(MAKE) -C servomoteur clean
	$(MAKE) -C spi clean

1wire: 
	$(MAKE) -C 1wire

i2c:
	$(MAKE) -C i2c

rs232:
	$(MAKE) -C rs232
